[package]
name = "jrsonnet-tokenizer"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
logos.workspace = true
nom.workspace = true

[lints]
workspace = true
