on: [ push, pull_request ]
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
      - uses: auguwu/clippy-action@1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      checks: write
